title: "Hiba Qutbuddin Habib"
description: "M.Sc. Student in Computer Science at KTH Royal Institute of Technology"
logo: "/assets/IMG_1507_round.png"  # Sökvägen till din bild
email: hibqut1@gmail.com
phone: "+46 700374460"
linkedin: "https://www.linkedin.com/in/hiba-qutbuddin-habib-713734231/"
github: "https://github.com/HQUT?tab=repositories"

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

show_downloads: false
