tittle: Hiba Qutbuddin Habib
logo: /assets/IMG_1507_round.png
email: hibqut1@gmail.com
phone: "+46 700374460"
linkedin: "https://www.linkedin.com/in/hiba-qutbuddin-habib-713734231/"
github: "https://github.com/HQUT?tab=repositories"
#remote_theme: pages-themes/minimal@v0.2.0
theme: jekyll-theme-minimal
plugins:
- jekyll-remote-theme
gem "github-pages", group: :jekyll_plugins


#description: [A short description of your site's purpose]
